### ISSUE TITLE
splittransaction löscht Umsatz

### ISSUE THREAD

**Issue by kosth44** [ds10git/hibiscus.splittransaction#2]
Seit kurzem splittet splittransaction den Umsatz nicht mehr auf sondern löscht ihn komplett.
Auszug aus log-Datei 
`[Tue Sep 12 11:54:07 CEST 2023][ERROR][main][de.willuhn.jameica.gui.GUI.loop] main loop crashed, retry
java.lang.NoSuchMethodError: de.willuhn.jameica.hbci.messaging.ObjectDeletedMessage: method 'void <init>(de.willuhn.datasource.GenericObject)' not found
	at hibiscus.splittransaction.DialogSplitTransaction$5.handleAction(DialogSplitTransaction.java:241)
	at de.willuhn.jameica.gui.parts.Button$1$1.run(Button.java:174)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at de.willuhn.jameica.gui.GUI$6.run(GUI.java:911)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4742)
	at de.willuhn.jameica.gui.GUI.startSync(GUI.java:907)
	at de.willuhn.jameica.gui.parts.Button$1.widgetSelected(Button.java:168)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog$4.run(AbstractDialog.java:564)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4742)
	at de.willuhn.jameica.gui.dialogs.AbstractDialog.open(AbstractDialog.java:489)
	at hibiscus.splittransaction.ContextMenuSplitTransaction$1.handleAction(ContextMenuSplitTransaction.java:60)
	at de.willuhn.jameica.gui.parts.ContextMenu$1.handleEvent(ContextMenu.java:183)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:928)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:331)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)
`

**Comment by ds10git** [comment]
Fixed with release 0.3.3.
